//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteCollatz.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IcontratoCollatz")]
    public interface IcontratoCollatz {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IcontratoCollatz/GetConjeturaCollatz", ReplyAction="http://tempuri.org/IcontratoCollatz/GetConjeturaCollatzResponse")]
        int[] GetConjeturaCollatz(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IcontratoCollatz/GetConjeturaCollatz", ReplyAction="http://tempuri.org/IcontratoCollatz/GetConjeturaCollatzResponse")]
        System.Threading.Tasks.Task<int[]> GetConjeturaCollatzAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IcontratoCollatz/GetSaludo", ReplyAction="http://tempuri.org/IcontratoCollatz/GetSaludoResponse")]
        string GetSaludo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IcontratoCollatz/GetSaludo", ReplyAction="http://tempuri.org/IcontratoCollatz/GetSaludoResponse")]
        System.Threading.Tasks.Task<string> GetSaludoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IcontratoCollatzChannel : ClienteCollatz.ServiceReference1.IcontratoCollatz, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IcontratoCollatzClient : System.ServiceModel.ClientBase<ClienteCollatz.ServiceReference1.IcontratoCollatz>, ClienteCollatz.ServiceReference1.IcontratoCollatz {
        
        public IcontratoCollatzClient() {
        }
        
        public IcontratoCollatzClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IcontratoCollatzClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcontratoCollatzClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcontratoCollatzClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] GetConjeturaCollatz(int numero) {
            return base.Channel.GetConjeturaCollatz(numero);
        }
        
        public System.Threading.Tasks.Task<int[]> GetConjeturaCollatzAsync(int numero) {
            return base.Channel.GetConjeturaCollatzAsync(numero);
        }
        
        public string GetSaludo() {
            return base.Channel.GetSaludo();
        }
        
        public System.Threading.Tasks.Task<string> GetSaludoAsync() {
            return base.Channel.GetSaludoAsync();
        }
    }
}
